### ISSUE TITLE
How can I sync this with pywal?

### ISSUE THREAD

**Issue by acron0** [RAR27/dyn-wall-rs#13]
I would like pywal to trigger every time the wallpaper changes.
```bash
wal -i "<current-wallpaper-path>" <other-options>
```

Is there a way to achieve this currently?

**Comment by rehanzo** [comment]
This should work:
```
dyn-wall-rs -a /path/to/dir -l $"wal -i ​\"​<current-wallpaper-path>​\"​ ​<​other-options​>"
```
Try that, and if it doesn't work, let me know.

**Comment by acron0** [comment]
But `"<current-wallpaper-path>"` should be whatever dyn-wall-rs has set the latest one to, right?

**Comment by rehanzo** [comment]
Whoops, yea, you're right. Sorry about that. Just confirming, are the quotation marks around the image path necessary to use pywal? If so, then you wouldn't be able to sync it with pywal. I'll look into having this more integrated within the program, so you could just tell it you want pywal to sync and it would do it without playing around with sending a custom command. I'll leave this open for now until I get that done.

**Comment by acron0** [comment]
No, pywal doesn't appear to require quotes :) thanks

**Comment by rehanzo** [comment]
Oh, in that case, you can use pywal, but you wouldn't be able to apply the extra options. Try this: 
```
dyn-wall-rs -a /path/to/dir -l "wal -i"
```

**Comment by acron0** [comment]
```
Error while running wal -i
```
:(

EDIT: Seems to work fine with "echo" so maybe an env problem, I'll have a fiddle
EDIT: Nevermind, I got it :) :+1: It wasn't getting `wal` off PATH so I gave it absolute path

**Comment by rehanzo** [comment]
Glad that's solved. I'll still leave this open though, because I feel like I should have the program allow for additional arguments so that you can include other options. Ill still also probably internalize the running of an extra program so it's less work for the user. I'll close this once that's done. Thanks for reporting the issue!

**Comment by rehanzo** [comment]
I have added the ability to add additional arguments after the argument of the path of the wallpaper is sent (#18). For details, have a look at the README, under Usage. With respect to internalizing running certain programs, I feel like that would add a level of complexity that would not make it worth implementing in my eyes, so I've decided against that. Thanks for creating the issue!
