### ISSUE TITLE
Can't set background without root permissions

### ISSUE THREAD

**Issue by acron0** [RAR27/dyn-wall-rs#14]
Me again!

So, I have no trouble using `feh` to set background, and `dyn-wall-rs` runs fine, no errors, and reports that it has set the background...but it doesn't actually change. Running with root permissions (`sudo`) fixes this problem.

```
 λ ls -al /home/acron/.cargo/bin/ | grep dyn
-rwsrwxr-x 1 acron acron 1321000 Jun 18 10:20 dyn-wall-rs
```

Is it me?

**Comment by rehanzo** [comment]
What DE are you using?

**Comment by acron0** [comment]
Gnome on Ubuntu

**Comment by rehanzo** [comment]
So with DE's like gnome, it actually doesn't use feh, but it runs a command that changes the background using commands that gnome provides. That command is:
```
gsettings set org.gnome.desktop.background picture-uri 'file:///path/to/image'
```
To my knowledge, this doesn't require root, but I may be wrong. Try setting the background using that command in terminal and see if it needs root. I'll get gnome for myself running soon (repasting cpu right now) and try to test it as well.

**Comment by acron0** [comment]
This didn't work, with or without root. I use i3wm and although I haven't seen a solid explanation as to _why_, the general consensus seems to be that you need to use a program to set the background image. I use `feh` in my config now. Perhaps an arg to `dyn-wall-rs` to force a particular program/routine? (e.g. `--backend feh`)

**Comment by rehanzo** [comment]
Interesting. What is the output of:
```
echo $XDG_CURRENT_DESKTOP
```

Also, try that command with Sudo, and let me know the output of both.

**Comment by acron0** [comment]
```
λ echo $XDG_CURRENT_DESKTOP                                         
GNOME

λ sudo gsettings set org.gnome.desktop.background picture-uri "/home/acron/Pictures/backgrounds/lakeside/08.png"

```

No output from second command and nothing changes.

**Comment by rehanzo** [comment]
What I meant is trying this:
```
Sudo echo $XDG_CURRENT_DESKTOP
```
Not sure if it'll return something different but if it does, that would explain it

**Comment by acron0** [comment]
Unfortunately, it does not! It still returns `GNOME`

**Comment by rehanzo** [comment]
Just in case, try running `sudo su`, and then run `echo $XDG_CURRENT_DESKTOP`

**Comment by acron0** [comment]
Ok, that's interesting, the response is empty.

```
λ sudo su
root@...:λ  echo $XDG_CURRENT_DESKTOP

root@...:λ  env | grep XDG

```
And no env vars about XDG at all. Conversely...

```
λ env | grep XDG
XDG_CONFIG_DIRS=/etc/xdg/xdg-i3:/etc/xdg
XDG_CURRENT_DESKTOP=GNOME
XDG_DATA_DIRS=/usr/share/i3:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=i3
XDG_SESSION_ID=4
XDG_SESSION_TYPE=x11
XDG_VTNR=2

```

**Comment by rehanzo** [comment]
Great, so know I know what's happening. I have it set so that if the XDG_CURRENT_DESKTOP variable isn't part of the list of supported desktop environments, then it uses feh. So it tries the gnome way when you don't run it with root, since the environment variable returns GNOME, but it uses feh when running as root, since the variable returns nothing. 

I guess the solution you proposed, with a `--backend` option seems like a good solution.  I'll go ahead and work in that, and I'll comment here when it's up.

**Comment by rehanzo** [comment]
Just added the ability to specify a backend ( #16 ). You can download the binary [here](https://github.com/RAR27/dyn-wall-rs/suites/821080737/artifacts/9059416) and try it out, or you can wait for the next release, which I will release when I add the ability to add extra arguments for user specified commands and whatnot. Thanks for reporting this issue!
