### ISSUE TITLE
Didn't you mean to divide and modulo here?

### ISSUE THREAD

**Issue by EmmChriss** [RAR27/dyn-wall-rs#2]
https://github.com/RAR27/dyn-wall-rs/blob/983c71cf39069e9efb39c984edd3c8e9fe2e9404/src/time_track.rs#L36-L48

It would be better to just
```rust
Time {
  total_mins,
  hours: total_mins / 60,
  mins: total_mins % 60
}
```

**Comment by rehanzo** [comment]
Thanks for submitting this issue!
Not sure how I didn't see doing this way. I have changed on 5f7b6f1 and pushed.
Thanks!
