### ISSUE TITLE
Readme and program arguments don't match

### ISSUE THREAD

**Issue by DavidLyhedDanielsson** [RAR27/dyn-wall-rs#20]
Love the support for running external commands! I noticed that in the readme the `-l` parameter is described as `-p`. Perhaps there are more outdated/changed things in the readme?

**Comment by rehanzo** [comment]
Hey! The README on the master branch is for the next version, which which release in the future. Sorry about the confusion!

**Comment by DavidLyhedDanielsson** [comment]
Oh, of course! I would have probably done the exact same thing :)
