### ISSUE TITLE
Add Feh scaling options to config file

### ISSUE THREAD

**Issue by qurriahSam** [RAR27/dyn-wall-rs#22]

**Comment by rehanzo** [comment]
Good idea! I'll get to adding this soon.

**Comment by rehanzo** [comment]
The feature has been pushed and will be in the next release. If you would like, you can download [this](https://github.com/RAR27/dyn-wall-rs/suites/946927546/artifacts/11765693) binary to use the feature right away. The details of using this feature can be found [here](https://github.com/RAR27/dyn-wall-rs/blob/update/README.md#usage). This feature is used through the backend option. 

Thanks for the feature suggestion!

**Comment by qurriahSam** [comment]
Thanks for your work

**Comment by rehanzo** [comment]
My pleasure!
