### ISSUE TITLE
Why is the elevation relevant for sunrise/sunset times? 

### ISSUE THREAD

**Issue by LeducH** [RAR27/dyn-wall-rs#24]
If I researched correctly on this [stack](https://math.stackexchange.com/questions/2186683/how-to-calculate-sunrise-and-sunset-times)  the author calculated the sun times with just longitude and latitude. 

Is it possible to omit the the elevation?

**Comment by rehanzo** [comment]
Hm, interesting. It definitely is possible, but it seems like adding elevation makes it more accurate. However, with a tool like this, accuracy isn't super important, and it may be worth it to simplify the use for the end user. What do you think?

**Comment by LeducH** [comment]
I agree that for this use case accuracy is one of the minor points. I would suggest to make it at least optional to add elevation. 

I went trough you code and was unsure how you currently do the calculation. 

could you please point me to the piece of code that does it?

**Comment by rehanzo** [comment]
I actually use the crate [sun-times](https://crates.io/crates/sun-times). However, it doesn't seem too hard to try to have this done internally. So I may either just default the elevation to 0 when no elevation is stated, or I may internalize the calculation and use just the latitude and longitude values.

**Comment by rehanzo** [comment]
Having an elevation value is now optional on the new release. I also opened a seperate issue for the internalizing of the calculation of the sunset and sunrise timings (#26). If you would like, you could try contributing that yourself, or I could get it done. Anyway, thanks for submitting the issue!
