### ISSUE TITLE
Don't use backend if none specified

### ISSUE THREAD

**Issue by marvin-sinister** [RAR27/dyn-wall-rs#25]
I have multiple screens and run `lxqt`. I want to use custom command to set background (`feh` with `--no-xinerama` option).
If i don't specify any backend `dyn-wall-rs` will set the background using `feh` (i assume), and will do it after running any programs specified.

So in my case if i define '`program = ["feh --no-xinerama --bg-scale "]`' and no backend, my background will be set to same scaled image on all screens, while if i specify '`backend = "xfce"`' I'll get correct image stretched across all screens.

Since i don't use xfce i suspect that my custom program is ran first and then overriden by default feh. In my opinion the correct approach would be to not use backend if not explicitly specified, or allow for '`none`' as an argument for backend.

**Comment by rehanzo** [comment]
This is similar to #22. You will be able to do this in the next release. If you can't wait, you can use the binary [here](https://github.com/RAR27/dyn-wall-rs/suites/946927546/artifacts/11765693). How it basically works is that through the backend option, you can specify a custom command. I'll keep this issue open until I release the next version.

**Comment by rehanzo** [comment]
This feature is out on the new release.
