### ISSUE TITLE
elevation causing error in command line and config file

### ISSUE THREAD

**Issue by gavsiu** [RAR27/dyn-wall-rs#27]
Firstly, is elevation in feet or meters? It's not stated anywhere and I can't find anything in your src.

Also, elevation seems to be causing this error:
```
Error with config file: the number of times listed in the config file does not equal the number of files in directory
```

This happens when I have a blank config file and lat, long, and elevation in the command line or everything specified in the config file. Removing elevation from the command line or commenting it out in the config file works for sun syncing.

I'm using 2.1.1 from AUR.

**Comment by gavsiu** [comment]
Actually, I don't think it had to do with elevation. I used the exact command without elevation just now and it gave the same error. I added back elevation and now it works only with elevation.

**Comment by rehanzo** [comment]
Hm, this seems like a tricky error. I'll play around with it and try to figure it out.

**Comment by carniz** [comment]
Not 100% sure of this, but it seems like alternating between starting with elevation enabled and elevation disabled solves the issue. 

For example: yesterday (daytime) I had to start with elevation enabled to avoid the "Error with config file" issue. This morning it was stuck with a 'night' image and the config that worked yesterday now yielded 

`Error with config file: the number of times listed in the config file does not equal the number of files in directory`

...when running `dyn-wall-rs --schedule`

After commenting out the elevation the issue went away.

**Comment by carniz** [comment]
Update: it seems as I don't get the "Error with config file: the number of times listed in the config file does not equal the number of files in directory" error when using a higher value for elevation.

This fails:
lat = 45.633331
long = 13.800000
elevation = 10

This works:
lat = 45.633331
long = 13.800000
elevation = 50

**Comment by rehanzo** [comment]
This is all good information. This issue seems quite tricky, but it is likely as a result of a logic error with relation to the determination of the specific times where the wallpaper changes. In certain scenarios it either has too many or too little timings. I'll get down to fixing this up soon.

**Comment by rehanzo** [comment]
Through my own testing, I believe this issue has been fixed in 79b4d57, but I would appreciate it if I could get you both to see if it fixes the issue for you? The binary with the fix can be found [here](https://github.com/RAR27/dyn-wall-rs/suites/1744757211/artifacts/33135629). I'll leave this issue open until I can get confirmation.Thank you!

**Comment by rehanzo** [comment]
With regards to your question about the elevation, it should be in meters above sea level. I'll make sure to mention that in the README and other relevant documentation.

**Comment by gavsiu** [comment]
Started running it. Will report in a few days unless an issue pops up before that.

**Comment by gavsiu** [comment]
I think it's safe to say the issue is fixed.

**Comment by rehanzo** [comment]
Good to hear. Thanks for helping me test!
