### ISSUE TITLE
Wrong argument program and config key program

### ISSUE THREAD

**Issue by maoxuner** [RAR27/dyn-wall-rs#30]
Command line argument `--program` and config key `program` not working.

According to your code [programs](https://github.com/RAR27/dyn-wall-rs/blob/657a46084083d6b58c7b6f8046d6f9c2c8f4d689/src/config.rs#L54), the right argument and config keyword must be `programs`.
```rust
    #[structopt(
        short = "p",
        long = "programs",
        value_name = "COMMAND",
        help = r#"Sends image as argument to command specified. Use alongside the directory option. If the command itself contains arguments, wrap in quotation ex. dyn-wall-rs -a /path/to/dir -l "betterlockscreen -u""#
    )]
    pub programs: Option<Vec<String>>,
```

The document and example configuration must be updated.

**Comment by RAR27** [comment]
Fixed. Thanks for reporting!
