### ISSUE TITLE
Backend xfce not working

### ISSUE THREAD

**Issue by maoxuner** [RAR27/dyn-wall-rs#31]
- When set backend to `xfce`, wallpaper was not changed.(I had changed wallpaper to any image not the right one.)
```bash
dyn-wall-rs -d /path/to/wallpapers -b xfce
```

- When set program to `xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP/workspace0/last-image -s`, wallpaper was changed.
```bash
dyn-wall-rs -d /path/to/wallpapers -p "xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP/workspace0/last-image -s"
```

---

xfce backdrop configurations:
```bash
$ xfconf-query -c xfce4-desktop -l
/backdrop/screen0/monitoreDP/workspace0/backdrop-cycle-enable
/backdrop/screen0/monitoreDP/workspace0/backdrop-cycle-period
/backdrop/screen0/monitoreDP/workspace0/color-style
/backdrop/screen0/monitoreDP/workspace0/image-style
/backdrop/screen0/monitoreDP/workspace0/last-image
/backdrop/screen0/monitoreDP/workspace0/rgba1
/backdrop/screen0/monitoreDP/workspace1/color-style
/backdrop/screen0/monitoreDP/workspace1/image-style
/backdrop/screen0/monitoreDP/workspace1/last-image
/backdrop/screen0/monitoreDP/workspace2/color-style
/backdrop/screen0/monitoreDP/workspace2/image-style
/backdrop/screen0/monitoreDP/workspace2/last-image
/backdrop/screen0/monitoreDP/workspace3/color-style
/backdrop/screen0/monitoreDP/workspace3/image-style
/backdrop/screen0/monitoreDP/workspace3/last-image
/backdrop/single-workspace-mode
/backdrop/single-workspace-number
/last/window-height
/last/window-width
```

**Comment by RAR27** [comment]
Could you test [this](https://github.com/RAR27/dyn-wall-rs/suites/2693265839/artifacts/59348885) build and let me know if it works?

**Comment by maoxuner** [comment]
> Could you test [this](https://github.com/RAR27/dyn-wall-rs/suites/2693265839/artifacts/59348885) build and let me know if it works?

I've tested. It works well now.

**Comment by RAR27** [comment]
> > Could you test [this](https://github.com/RAR27/dyn-wall-rs/suites/2693265839/artifacts/59348885) build and let me know if it works?
> 
> I've tested. It works well now.

Great. I'll have that fix out with next release. Thanks for reporting the issue. Appreciate it.
